
spring:
  profiles:
    active:
    - test
    - monitor
---
#jdbc:mysql://127.0.0.1/ssh_test,com.mysql.jdbc.Driver
spring:
  profiles: dev
  datasource:
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 3
  thymeleaf:
    cache: false
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: kdxnlyaphvgsbjcc
    protocol: smtp
    username: 535211279@qq.com
    properties:
      smtp:
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000
        
logging:
  level:
    com.entor.erp: debug
server:
  port: 80
druid:
  view:
    servletUsername: ganxiaofeng
    servletPassword: root
mybatis-plus:
  mapper-locations: classpath:/com/entor/erp/dao/*.mapper
  global-config:
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator

---

spring:
  profiles: test
  datasource:
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 3
  thymeleaf:
    cache: false
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: kdxnlyaphvgsbjcc
    protocol: smtp
    username: 535211279@qq.com
    properties:
      smtp:
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000
        
logging:
  level:
    com.entor.erp: debug
server:
  port: 8080
druid:
  view:
    servletUsername: ganxiaofeng
    servletPassword: root
mybatis-plus:
  mapper-locations: classpath:/com/entor/erp/dao/*.mapper
  global-config:
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator