
spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/ssh_test
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 3
  thymeleaf:
    cache: false
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - classpath:/templates/
server:
  port: 80
druid:
  view:
    servletUsername: ganxiaofeng
    servletPassword: root
  monitor:
    serviceAndDaoId:
    - userServiceImpl
mybatis-plus:
  mapper-locations: classpath:/com/entor/erp/dao/*.mapper